name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Clear pip cache
      run: |
        pip cache purge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 .
    
    - name: Static type checking with mypy
      run: |
        mypy --explicit-package-bases src/
    - name: Test with pytest and coverage
      run: |
        pytest --cov=src --cov-fail-under=80
    - name: Security scan with bandit
      run: |
        bandit -r src
    - name: Dependency scan with safety
      run: |
        safety check -r requirements.txt
